import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Email } from '@/components/Email'
const inter = Inter({ subsets: ['latin'] })
import { render } from "@react-email/render";
import {
  Button,
  Alert,
  AlertIcon,
  AlertTitle,
  AlertDescription,
  Portal,
  Input,
  Box,
  Tabs,
  TabList,
  TabPanels,
  Tab,
  TabPanel,
  Form,
  FormControl,
  FormLabel,
  FormErrorMessage,
  FormHelperText,
  Textarea
} from '@chakra-ui/react'
import { useEffect, useRef, useState } from 'react'

const SUBJECT = "subject"
const TEXT = "text"
const PREVIEW = "preview"
const PASSWORD = "password"


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        as="main"
        w="100%"
        minH="100vh"
      >
        <Tabs>
          <TabList
            m="0 auto"
            transform={"translateX(-50px)"}
            maxW="350px"
          >
            <Tab flex={1}>Send email</Tab>
            <Tab flex={1}>Settings</Tab>
            <Tab flex={1}>Preview</Tab>
          </TabList>

          <TabPanels>
            <TabPanel
            >
              <Container>
                <Box>
                  <SendEmailForm />
                </Box>
              </Container>
            </TabPanel>
            <TabPanel>
              <Container>
                <Settings />
              </Container>
            </TabPanel>
            <TabPanel>
              <PreviewEmail />
            </TabPanel>
          </TabPanels>

        </Tabs>
      </Box>
    </>
  )
}

function Settings() {
  const [subject, setSubject] = useState("");
  const [text, setText] = useState("");
  const [preview, setPreview] = useState("");
  const [password, setPassword] = useState("");

  const [isSaving, setIsSaving] = useState(false)

  useEffect(() => {
    const savedSubject = localStorage.getItem(SUBJECT);
    const savedText = localStorage.getItem(TEXT);
    const savedPreview = localStorage.getItem(PREVIEW);
    const savedPassword = localStorage.getItem(PASSWORD);

    if (savedSubject) {
      setSubject(() => savedSubject);
    }

    if (savedText) {
      setText(() => savedText);
    }

    if (savedPreview) {
      setPreview(() => savedPreview);
    }

    if (savedPassword) {
      setPassword(() => savedPassword);
    }

  }, [])

  return (
    <Box
      w="100%"
      display={"flex"}
      flexDir={"column"}
      as={"form"}
      gap={"35px"}
      onSubmit={(e) => {
        setIsSaving(true)
        e.preventDefault()
        localStorage.setItem(SUBJECT, subject);
        localStorage.setItem(TEXT, text)
        localStorage.setItem(PREVIEW, preview)
        localStorage.setItem(PASSWORD, password)
        setIsSaving(false)
      }}
    >
      <FormControl>
        <FormLabel>Email subject</FormLabel>
        <Input
          onChange={(e) => setSubject(e.target.value)}
          value={subject} type='text' />
      </FormControl>
      <FormControl>
        <FormLabel>Email text</FormLabel>
        <Input
          onChange={(e) => setText(e.target.value)}
          value={text} type='text' />
      </FormControl>
      <FormControl>
        <FormLabel>Preview</FormLabel>
        <Textarea
          onChange={(e) => setPreview(e.target.value)}
          value={preview}
          placeholder='Buy program or I murder ur mum'
        />
        <FormHelperText>Email clients have this concept of “preview text” which gives insight into what’s inside the email before you open. A good practice is to keep that text under 90 characters.</FormHelperText>
      </FormControl>
      <FormControl>
        <FormLabel>Passowrd</FormLabel>
        <Input
          onChange={(e) => setPassword(e.target.value)}
          value={password}
          type="text"
          placeholder='1234'
        />
      </FormControl>
      <CustomButton isSending={isSaving}>
        Save
      </CustomButton>
    </Box>
  )
}

function Container({ children, ...styles }) {
  return (
    <Box
      maxW="900px"
      m="0 auto"
      minH="100%"
      display={"flex"}
      alignItems={"center"}
      marginTop={"200px"}
      justifyContent={"center"}
    >
      {children}
    </Box>
  )
}

function CustomButton({ children, ...styles }) {
  return (
    <Button
      className={`${styles.button}`}
      type='submit'
      bg="green.500"
      maxH="50px"
      w="200px"
      _hover={{
        backgroundColor: "green.400"
      }}
      {...styles}
    >{children}</Button>
  )
}

function PreviewEmail() {
  const html = render(<Email />, {
    pretty: true
  });
  return (
    <div dangerouslySetInnerHTML={{ __html: html }} />
  );
}

function SendEmailForm() {
  const [isSending, setIsSending] = useState();
  const [success, setSuccess] = useState();
  const [showAlert, setShowAlert] = useState(false);
  const [alertText, setAlertText] = useState("")
  const inputRef = useRef();

  useEffect(() => {

    let timer;
    function closeAlert() {
      timer = setTimeout(() => {
        setShowAlert(false)
        setAlertText("")
      }, 4000);
    }

    closeAlert()

    return () => {
      clearTimeout(timer)
    }

  }, [showAlert])


  return (
    <Box
      display={"flex"}
      gap="5px"
      width={{
        base: "100%",
        lg: "800px"
      }}
      as="form"
      onSubmit={async (e) => {
        e.preventDefault()
        const subject = localStorage.getItem(SUBJECT)
        const text = localStorage.getItem(TEXT)
        const preview = localStorage.getItem(PREVIEW)
        const password = localStorage.getItem(PASSWORD)


        if (!subject) {
          setShowAlert(true)
          setAlertText("Please set subject in settings!");
          return
        }

        if (!text) {
          setShowAlert(true)
          setAlertText("Please set text in settings!");
          return
        }

        if (!preview) {
          setShowAlert(true)
          setAlertText("Please set preview in settings!");
          return
        }

        if (!password) {
          setShowAlert(true)
          setAlertText("Please set password in settings!");
          return
        }

        setIsSending(true);
        const html = render(<Email preview={preview} />, {
          pretty: true
        });
        const url = `/api/sendEmail/${inputRef.current.value}`;

        const res = await fetch(url, {
          method: "post",
          mode: "no-cors",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            html,
            settingsData: {
              subject,
              text,
              password
            }
          }),
        });

        if (res.ok) {
          setSuccess(true);
        } else {
          setSuccess(false)
        }

        setShowAlert(true)
        setIsSending(false)
      }}
    >
      <Input
        type='email'
        placeholder='Enter email of the customer'
        required
        minLength={1}
        colorScheme='gray'
        _active={{
          borderCOlor: "white"
        }}
        _focusVisible={{
          borderColor: "white"
        }}
        ref={inputRef}
      />

      <CustomButton
        isLoading={isSending}
      >Send</CustomButton>
      {showAlert && <Portal zIndex={100}>
        <Alert
          zIndex={100}
          bg={success === true ? "green.500" : "red.500"}
          status={success === true ? 'success' : 'error'}
          variant='subtle'
          flexDirection='column'
          alignItems='center'
          justifyContent='center'
          textAlign='center'
          height='200px'
          position={"absolute"}
          bottom={0}
          left={"50%"}
          transform={"translateX(-50%)"}
          color={"white"}
          fontSize={"24px"}
          gap="15px"
        >
          <AlertIcon width={"35px"} height={"35px"} />
          <AlertTitle>{success === true ? "Email was sent successfully!" : "Error sending email!"}</AlertTitle>
          <AlertDescription>{alertText}</AlertDescription>
        </Alert>
      </Portal>}
    </Box>
  )
}
